name: Iris ML CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"  # Using Python 3.9

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-dev build-essential

      - name: Install Python Dependencies
        run: |
          pip install --upgrade pip  # Upgrade pip to avoid installation issues
          pip install -r requirements.txt  # Install dependencies from the requirements.txt

      - name: Run Tests
        run: |
          pytest tests/  # Run tests to validate the pipeline

      - name: Build Model
        run: |
          python train.py  # Train the machine learning model (assuming you have a train.py script)

      - name: Upload Model (Optional)
        uses: actions/upload-artifact@v2
        with:
          name: iris-model
          path: model.pkl  # Assuming the trained model is saved as 'model.pkl'
