name: Iris ML CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # Updated to v3

      - name: Set up Python
        uses: actions/setup-python@v3  # Updated to v3
        with:
          python-version: "3.9"  # Using Python 3.9

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-dev build-essential

      - name: Install Python Dependencies
        run: |
          pip install --upgrade pip  # Upgrade pip to avoid installation issues
          pip install -r requirements.txt  # Install dependencies from the requirements.txt

      - name: Add src directory to Python path
        run: |
          echo "PYTHONPATH=$(pwd)/src" >> $GITHUB_ENV  # Ensure src is on the Python path

      - name: Run Tests
        run: |
          pytest tests/  # Run tests to validate the pipeline

      - name: Build Model
        run: |
          python src/train.py  # Train the machine learning model (assuming you have a train.py script)

      - name: Upload Model (Optional)
        uses: actions/upload-artifact@v3  # Updated to v3
        with:
          name: iris-model
          path: artifacts/model.pkl  # Assuming the trained model is saved as 'model.pkl'
